spring:
  application:
    name: backend

  profiles:
    active: default

  # Defines the JDBC connection to the medtrack database
  datasource:
    url: jdbc:postgresql://localhost:5432/medtrack
    driver-class-name: org.postgresql.Driver
    username: medtrack_user
    password: Bp34syw2j@

  # Disables the schema manager provided by Hibernate because Liquibase will handle the migrations
  jpa:
    hibernate:
      ddl-auto: none # Good to manage schema manually
    show-sql: true # Shows SQL in the console
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Activates the liquibase and points to the master.xml
  liquibase:
    default-schema: public
    liquibase-schema: public
    enabled: true
    change-log: classpath:db/changelog/master.xml

  config:
    import:
      - "optional:dotenv:file:./.env" #Load the file .env from the JVM's working directory (project root)

server:
  port: 8443 #The port on which the server is listening
  ssl:
    key-store: classpath:springboot.p12 #Path to the key store that contains the SSL certificate
    key-store-password: password #Password to access the key store
    key-store-type: PKCS12
    key-alias: springboot #How the key is identified in the key store
    key-password: password #Password to access the key in the key store

jwt:
  access-token-ttl-seconds: 1800 #30 minutes
  refresh-token-ttl-seconds: 86400 #1 day
  secretKey: ${JTW_SECRET}
  issuer: login-auth-api

debug: false


